spring:
  application:
    name: gateway-service

  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: test_keyspace
    schema-action: none

server:
  port: 8888

swagger:
  server-url: http://localhost:8888

product-offer:
  api-url: http://localhost:9999

available-offers:
  outbox:

